
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretLicenseName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  nxrm-license.lic: {{ .Files.Get (printf "secrets/%s.lic" .Values.secretLicenseName) | b64enc }}
