#*******************************************************************************
# Copyright (c) 2023 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: {{ .Values.namespace }}
  annotations:
    haproxy.router.openshift.io/timeout: 60s
    haproxy.router.openshift.io/disable_cookies: 'true'
  name: {{ .Values.appName }}
spec:
  host: {{ .Values.host }}
  path: /
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: "Service"
    name: "{{ .Values.appName }}"
    weight: 100
